include theos/makefiles/common.mk

BUNDLE_NAME = DemoWidget
DemoWidget_FILES = DemoWidget.m
DemoWidget_INSTALL_PATH = /Library/Application Support/Widge/Widgets
DemoWidget_FRAMEWORKS = UIKit
DemoWidget_OBJ_FILES = ../framework/obj/WidgeKit

include $(THEOS_MAKE_PATH)/bundle.mk